version: "3.9"

services:
  # app:
  #   image: node:24-alpine
  #   container_name: wb-app
  #   working_dir: /app

  #   volumes:
  #     - .:/app

  #   ports:
  #     - "3000:3000"

  #   environment:
  #     WATCHPACK_POLLING: true

  #   command: sh -c "npm install && npm run dev -- -H 0.0.0.0"

  #   depends_on:
  #     - mongodb

  mongodb:
    image: mongo:7
    container_name: wb-mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
